### PR TITLE
Less silly remote config

### PR DESCRIPTION
**Pull request by Raynos**
Three changes:

 - default lazy to true
 - Only update the state of the world AFTER loading file
 - Fix a timeout troll thingy.

r: @jcorbin @rf @kriskowal

### CODE REVIEW

**Comment by jcorbin** [comment]
lgtm once past test

**Comment by Raynos** [comment]
Dont know why test fails :(

**Comment by rf** [comment]
The tests all pass, multi_bench just fails with econnrefused

**Comment by Raynos** [comment]
#passed #move along

**Pull request merged**
