### PR TITLE
Update hostports tests for thriftrw 3.0.1

### PR DESCRIPTION
**Pull request by malandrew**
PR to get tests for tchannel-node to pass after upgrading to thriftrw 3.0.1

### CODE REVIEW

**Comment by kriskowal** [comment]
I I don’t think it will be adequate to fix this in hyperbahn. To appease the tests (and satisfy backward compatibility) we will need to address the issue in TChannel node by coercing the old usage.

**Comment by malandrew** [comment]
so support `{source: ... }`? Can we just major version bump?

**Comment by kriskowal** [comment]
@malandrew It’s become clear that major version bumps are expensive since we have to backport fixes to prior major versions of tchannel.

**Comment by Raynos** [comment]
did this get merged somewhere else ?

**Comment by Raynos** [comment]
I dont think this is necessary; going to close.

**Pull request closed without merging**
