### PR TITLE
Do incremental work under ServiceProxy#removeServicePeer

### PR DESCRIPTION
**Pull request by jcorbin**
Use partialRange.removeWorker rather than sorting all service workers.

### CODE REVIEW

**Comment by jcorbin** [comment]
Going to block and rebase on https://github.com/uber/hyperbahn/pull/250 since it adds more coverage to the affected path.

**Comment by Raynos** [comment]
I trust the method does what it says on the tin.

**Comment by jcorbin** [comment]
it does, and it's already used by the other way that we remove workers under the peer reaper: https://github.com/uber/hyperbahn/blob/master/service-proxy.js#L1471

**Comment by jcorbin** [comment]
Amusingly enough, this method did not work as advertised; fixed in #267.

**Pull request merged**
